name: CodeChavez M3diator Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore **/CodeChavez.M3diator/CodeChavez.M3diator.csproj --configfile nuget.config --no-cache

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests with coverage
        run: |
          dotnet test **/*Tests.csproj \
            --no-build --configuration Release \
            --collect:"XPlat Code Coverage" \
            --results-directory ./TestResults \
            /p:CoverletOutputFormat=cobertura

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ./TestResults/**/coverage.cobertura.xml

      - name: Report coverage to GitHub PR (optional)
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./TestResults/**/coverage.cobertura.xml
          badge: true
          format: markdown
          output: both

  build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore **/CodeChavez.M3diator/CodeChavez.M3diator.csproj --configfile nuget.config --no-cache

      - name: Build project
        run: dotnet build **/CodeChavez.M3diator/CodeChavez.M3diator.csproj --configuration Release

      - name: Package 
        run: dotnet pack **/CodeChavez.M3diator/CodeChavez.M3diator.csproj --configuration Release --no-build --output ./artifacts

      - name: Push NuGet package
        run: dotnet nuget push "./artifacts/*.nupkg" --api-key $NUGET_AUTH_TOKEN --source https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
          